---
- name: Configure webserver
  hosts: all

  tasks:
  - name: Ensure Apache is installed
    become: yes
    ansible.builtin.package:
      name: httpd
      state: present
  - name: Ensure Apache is started
    become: yes
    ansible.builtin.service:
      name: httpd
      state: started
  - name: Add dummy HTML
    become: yes
    ansible.builtin.template:
      src: ./rsc/index.html.j2
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: '0440'